version: "3"
services:
  reconattendplus_registration:
    build: ./registration
    container_name: reconattendplus_registration
    restart: always
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=mongodb+srv://laksh:blackwinsreconattendplus@cluster0.3d4mfoc.mongodb.net/?retryWrites=true&w=majority
    # depends_on:
    #   - mongodb

  reconattendplus_attendance:
    build: ./attendance
    container_name: reconattendplus_attendance
    restart: always
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=mongodb+srv://laksh:blackwinsreconattendplus@cluster0.3d4mfoc.mongodb.net/?retryWrites=true&w=majority
    # depends_on:
    #   - mongodb

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

volumes:
  mongodb_data:
